import Head from "next/head";
import { getRandomHeadline } from "@whitep4nth3r/get-random-headline";
import { getRandomTechBusinessName } from "@whitep4nth3r/get-random-tech-business-name";
import { buildUniqueIntArray } from "../tools/utils";
import { getRandomUsps } from "../tools/usp";
import { getRandomCtas } from "../tools/cta";

import {
  AcademicCapIcon,
  AdjustmentsIcon,
  AnnotationIcon,
  ArrowCircleDownIcon,
  ArrowCircleLeftIcon,
  ArrowCircleRightIcon,
  ArrowCircleUpIcon,
  ArrowDownIcon,
  ArrowLeftIcon,
  ArrowNarrowDownIcon,
  ArrowNarrowLeftIcon,
  ArrowNarrowRightIcon,
  ArrowNarrowUpIcon,
  ArrowRightIcon,
  ArrowSmDownIcon,
  ArrowSmLeftIcon,
  ArrowSmRightIcon,
  ArrowSmUpIcon,
  ArrowUpIcon,
  AtSymbolIcon,
  BackspaceIcon,
  BadgeCheckIcon,
  BanIcon,
  BeakerIcon,
  BellIcon,
  BookOpenIcon,
  BookmarkAltIcon,
  BookmarkIcon,
  BriefcaseIcon,
  CakeIcon,
  CalculatorIcon,
  CalendarIcon,
  CameraIcon,
  CashIcon,
  ChartBarIcon,
  ChartPieIcon,
  ChartSquareBarIcon,
  ChatAlt2Icon,
  ChatAltIcon,
  ChatIcon,
  CheckCircleIcon,
  CheckIcon,
  ChevronDoubleDownIcon,
  ChevronDoubleLeftIcon,
  ChevronDoubleRightIcon,
  ChevronDoubleUpIcon,
  ChevronDownIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronUpIcon,
  ChipIcon,
  ClipboardCheckIcon,
  ClipboardCopyIcon,
  ClipboardListIcon,
  ClockIcon,
  CloudDownloadIcon,
  CloudUploadIcon,
  CloudIcon,
  CodeIcon,
  CogIcon,
  CollectionIcon,
  ColorSwatchIcon,
  CreditCardIcon,
  CubeTransparentIcon,
  CubeIcon,
  CurrencyBangladeshiIcon,
  CurrencyDollarIcon,
  CurrencyEuroIcon,
  CurrencyPoundIcon,
  CurrencyRupeeIcon,
  CurrencyYenIcon,
  CursorClickIcon,
  DatabaseIcon,
  DesktopComputerIcon,
  DeviceMobileIcon,
  DeviceTabletIcon,
  DocumentAddIcon,
  DocumentDownloadIcon,
  DocumentDuplicateIcon,
  DocumentRemoveIcon,
  DocumentReportIcon,
  DocumentSearchIcon,
  DocumentTextIcon,
  DocumentIcon,
  DotsCircleHorizontalIcon,
  DotsHorizontalIcon,
  DotsVerticalIcon,
  DownloadIcon,
  DuplicateIcon,
  EmojiHappyIcon,
  EmojiSadIcon,
  ExclamationCircleIcon,
  ExclamationIcon,
  ExternalLinkIcon,
  EyeOffIcon,
  EyeIcon,
  FastForwardIcon,
  FilmIcon,
  FilterIcon,
  FingerPrintIcon,
  FireIcon,
  FlagIcon,
  GiftIcon,
  GlobeAltIcon,
  GlobeIcon,
  HandIcon,
  HashtagIcon,
  HeartIcon,
  HomeIcon,
  IdentificationIcon,
  InboxInIcon,
  InboxIcon,
  InformationCircleIcon,
  KeyIcon,
  LibraryIcon,
  LightBulbIcon,
  LightningBoltIcon,
  LinkIcon,
  LocationMarkerIcon,
  LockClosedIcon,
  LockOpenIcon,
  LoginIcon,
  LogoutIcon,
  MailOpenIcon,
  MailIcon,
  MapIcon,
  MoonIcon,
  MusicNoteIcon,
  NewspaperIcon,
  OfficeBuildingIcon,
  PaperAirplaneIcon,
  PaperClipIcon,
  PauseIcon,
  PencilAltIcon,
  PencilIcon,
  PhoneIncomingIcon,
  PhoneMissedCallIcon,
  PhoneOutgoingIcon,
  PhoneIcon,
  PhotographIcon,
  PlayIcon,
  PresentationChartBarIcon,
  PresentationChartLineIcon,
  PrinterIcon,
  PuzzleIcon,
  QrcodeIcon,
  QuestionMarkCircleIcon,
  ReceiptRefundIcon,
  ReceiptTaxIcon,
  RefreshIcon,
  ReplyIcon,
  RewindIcon,
  RssIcon,
  SaveAsIcon,
  SaveIcon,
  ScaleIcon,
  ScissorsIcon,
  SearchCircleIcon,
  SearchIcon,
  SelectorIcon,
  ServerIcon,
  ShareIcon,
  ShieldCheckIcon,
  ShieldExclamationIcon,
  ShoppingBagIcon,
  ShoppingCartIcon,
  SortAscendingIcon,
  SortDescendingIcon,
  SparklesIcon,
  SpeakerphoneIcon,
  StarIcon,
  StatusOfflineIcon,
  StatusOnlineIcon,
  StopIcon,
  SunIcon,
  SupportIcon,
  SwitchHorizontalIcon,
  SwitchVerticalIcon,
  TableIcon,
  TagIcon,
  TemplateIcon,
  TerminalIcon,
  ThumbDownIcon,
  ThumbUpIcon,
  TicketIcon,
  TrashIcon,
  TrendingDownIcon,
  TrendingUpIcon,
  TruckIcon,
  UploadIcon,
  VariableIcon,
  VideoCameraIcon,
  ViewBoardsIcon,
  ViewGridAddIcon,
  ViewGridIcon,
  ViewListIcon,
  VolumeOffIcon,
  VolumeUpIcon,
  WifiIcon,
  XCircleIcon,
  XIcon,
  ZoomInIcon,
  ZoomOutIcon,
} from "@heroicons/react/solid";

const svgComponents = [
  <AcademicCapIcon />,
  <AdjustmentsIcon />,
  <AnnotationIcon />,
  <ArrowCircleDownIcon />,
  <ArrowCircleLeftIcon />,
  <ArrowCircleRightIcon />,
  <ArrowCircleUpIcon />,
  <ArrowDownIcon />,
  <ArrowLeftIcon />,
  <ArrowNarrowDownIcon />,
  <ArrowNarrowLeftIcon />,
  <ArrowNarrowRightIcon />,
  <ArrowNarrowUpIcon />,
  <ArrowRightIcon />,
  <ArrowSmDownIcon />,
  <ArrowSmLeftIcon />,
  <ArrowSmRightIcon />,
  <ArrowSmUpIcon />,
  <ArrowUpIcon />,
  <AtSymbolIcon />,
  <BackspaceIcon />,
  <BadgeCheckIcon />,
  <BanIcon />,
  <BeakerIcon />,
  <BellIcon />,
  <BookOpenIcon />,
  <BookmarkAltIcon />,
  <BookmarkIcon />,
  <BriefcaseIcon />,
  <CakeIcon />,
  <CalculatorIcon />,
  <CalendarIcon />,
  <CameraIcon />,
  <CashIcon />,
  <ChartBarIcon />,
  <ChartPieIcon />,
  <ChartSquareBarIcon />,
  <ChatAlt2Icon />,
  <ChatAltIcon />,
  <ChatIcon />,
  <CheckCircleIcon />,
  <CheckIcon />,
  <ChevronDoubleDownIcon />,
  <ChevronDoubleLeftIcon />,
  <ChevronDoubleRightIcon />,
  <ChevronDoubleUpIcon />,
  <ChevronDownIcon />,
  <ChevronLeftIcon />,
  <ChevronRightIcon />,
  <ChevronUpIcon />,
  <ChipIcon />,
  <ClipboardCheckIcon />,
  <ClipboardCopyIcon />,
  <ClipboardListIcon />,
  <ClockIcon />,
  <CloudDownloadIcon />,
  <CloudUploadIcon />,
  <CloudIcon />,
  <CodeIcon />,
  <CogIcon />,
  <CollectionIcon />,
  <ColorSwatchIcon />,
  <CreditCardIcon />,
  <CubeTransparentIcon />,
  <CubeIcon />,
  <CurrencyBangladeshiIcon />,
  <CurrencyDollarIcon />,
  <CurrencyEuroIcon />,
  <CurrencyPoundIcon />,
  <CurrencyRupeeIcon />,
  <CurrencyYenIcon />,
  <CursorClickIcon />,
  <DatabaseIcon />,
  <DesktopComputerIcon />,
  <DeviceMobileIcon />,
  <DeviceTabletIcon />,
  <DocumentAddIcon />,
  <DocumentDownloadIcon />,
  <DocumentDuplicateIcon />,
  <DocumentRemoveIcon />,
  <DocumentReportIcon />,
  <DocumentSearchIcon />,
  <DocumentTextIcon />,
  <DocumentIcon />,
  <DotsCircleHorizontalIcon />,
  <DotsHorizontalIcon />,
  <DotsVerticalIcon />,
  <DownloadIcon />,
  <DuplicateIcon />,
  <EmojiHappyIcon />,
  <EmojiSadIcon />,
  <ExclamationCircleIcon />,
  <ExclamationIcon />,
  <ExternalLinkIcon />,
  <EyeOffIcon />,
  <EyeIcon />,
  <FastForwardIcon />,
  <FilmIcon />,
  <FilterIcon />,
  <FingerPrintIcon />,
  <FireIcon />,
  <FlagIcon />,
  <GiftIcon />,
  <GlobeAltIcon />,
  <GlobeIcon />,
  <HandIcon />,
  <HashtagIcon />,
  <HeartIcon />,
  <HomeIcon />,
  <IdentificationIcon />,
  <InboxInIcon />,
  <InboxIcon />,
  <InformationCircleIcon />,
  <KeyIcon />,
  <LibraryIcon />,
  <LightBulbIcon />,
  <LightningBoltIcon />,
  <LinkIcon />,
  <LocationMarkerIcon />,
  <LockClosedIcon />,
  <LockOpenIcon />,
  <LoginIcon />,
  <LogoutIcon />,
  <MailOpenIcon />,
  <MailIcon />,
  <MapIcon />,
  <MoonIcon />,
  <MusicNoteIcon />,
  <NewspaperIcon />,
  <OfficeBuildingIcon />,
  <PaperAirplaneIcon />,
  <PaperClipIcon />,
  <PauseIcon />,
  <PencilAltIcon />,
  <PencilIcon />,
  <PhoneIncomingIcon />,
  <PhoneMissedCallIcon />,
  <PhoneOutgoingIcon />,
  <PhoneIcon />,
  <PhotographIcon />,
  <PlayIcon />,
  <PresentationChartBarIcon />,
  <PresentationChartLineIcon />,
  <PrinterIcon />,
  <PuzzleIcon />,
  <QrcodeIcon />,
  <QuestionMarkCircleIcon />,
  <ReceiptRefundIcon />,
  <ReceiptTaxIcon />,
  <RefreshIcon />,
  <ReplyIcon />,
  <RewindIcon />,
  <RssIcon />,
  <SaveAsIcon />,
  <SaveIcon />,
  <ScaleIcon />,
  <ScissorsIcon />,
  <SearchCircleIcon />,
  <SearchIcon />,
  <SelectorIcon />,
  <ServerIcon />,
  <ShareIcon />,
  <ShieldCheckIcon />,
  <ShieldExclamationIcon />,
  <ShoppingBagIcon />,
  <ShoppingCartIcon />,
  <SortAscendingIcon />,
  <SortDescendingIcon />,
  <SparklesIcon />,
  <SpeakerphoneIcon />,
  <StarIcon />,
  <StatusOfflineIcon />,
  <StatusOnlineIcon />,
  <StopIcon />,
  <SunIcon />,
  <SupportIcon />,
  <SwitchHorizontalIcon />,
  <SwitchVerticalIcon />,
  <TableIcon />,
  <TagIcon />,
  <TemplateIcon />,
  <TerminalIcon />,
  <ThumbDownIcon />,
  <ThumbUpIcon />,
  <TicketIcon />,
  <TrashIcon />,
  <TrendingDownIcon />,
  <TrendingUpIcon />,
  <TruckIcon />,
  <UploadIcon />,
  <VariableIcon />,
  <VideoCameraIcon />,
  <ViewBoardsIcon />,
  <ViewGridAddIcon />,
  <ViewGridIcon />,
  <ViewListIcon />,
  <VolumeOffIcon />,
  <VolumeUpIcon />,
  <WifiIcon />,
  <XCircleIcon />,
  <XIcon />,
  <ZoomInIcon />,
  <ZoomOutIcon />,
];

export default function Home({ headline, businessName, svgComponentsIndexArray, usps, ctas }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <h1>{businessName}</h1>
        <p>{headline}</p>
        <div style={{ display: "grid", gridTemplateColumns: "1fr 1fr 1fr" }}>
          {svgComponentsIndexArray.map((int, index) => (
            <div key={int}>
              <div style={{ height: "20px", width: "20px" }}>{svgComponents[int]}</div>
              <h2>{usps[index]}</h2>
              <button type="button">{ctas[index]}</button>
            </div>
          ))}
        </div>
      </main>
    </>
  );
}

export const getServerSideProps = () => {
  const USP_COUNT = 3;
  const headline = getRandomHeadline();
  const businessName = getRandomTechBusinessName();
  const svgComponentsIndexArray = buildUniqueIntArray(USP_COUNT, svgComponents.length);
  const usps = getRandomUsps(USP_COUNT);
  const ctas = getRandomCtas(USP_COUNT);

  return {
    props: {
      headline,
      businessName,
      svgComponentsIndexArray,
      usps,
      ctas,
    },
  };
};
